name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build